Repository nimblehq/elixir-templates, pull requests merged in 2021-12, with the labels that each got.

#128 Override the Mime dependency
  .credo.exs
  lib/nimble_template/addons/variants/phoenix/web/wallaby.ex
  test/nimble_template/addons/variants/phoenix/web/wallaby_test.exs
Labels: priority : high, type : feature

#129 Skip node dependencies installation for API variant
  .github/workflows/test_api_variant_on_custom_api_project.yml
  .github/workflows/test_api_variant_on_standard_api_project.yml
  .github/workflows/test_live_variant_on_custom_liveview_project.yml
  .github/workflows/test_live_variant_on_standard_liveview_project.yml
  .github/workflows/test_variant_on_custom_web_project.yml
  .github/workflows/test_variant_on_standard_web_project.yml
  action.yml
Labels: type : bug

#133 Add Faker addon
  lib/nimble_template/addons/faker.ex
  lib/nimble_template/variants/mix/template.ex
  lib/nimble_template/variants/phoenix/template.ex
  test/nimble_template/addons/faker_test.exs
  test/nimble_template/addons/mimic_test.exs
Labels: type : feature

#117 Add Github Wiki add on for Web variant
  Makefile
  lib/nimble_template/addons/github.ex
  lib/nimble_template/helpers/github.ex
  lib/nimble_template/variants/mix/template.ex
  lib/nimble_template/variants/phoenix/template.ex
  priv/templates/nimble_template/.github/wiki/Getting-Started.md.eex
  priv/templates/nimble_template/.github/wiki/Getting-Started.md.mix.eex
  priv/templates/nimble_template/.github/wiki/Home.md
  priv/templates/nimble_template/.github/wiki/_Sidebar.md
  priv/templates/nimble_template/.github/workflows/publish_wiki.yml
  test/nimble_template/addons/github_test.exs
Labels: type : feature

#112 Update Github action workflows to align with our compass conventions
  .github/workflows/publish_to_hex_pm.yml
  .github/workflows/test_api_variant_on_custom_api_project.yml
  .github/workflows/test_api_variant_on_standard_api_project.yml
  .github/workflows/test_live_variant_on_custom_liveview_project.yml
  .github/workflows/test_live_variant_on_standard_liveview_project.yml
  .github/workflows/test_mix_variant_on_custom_mix_project.yml
  .github/workflows/test_mix_variant_on_custom_mix_project_with_supervision.yml
  .github/workflows/test_mix_variant_on_standard_mix_project.yml
  .github/workflows/test_mix_variant_on_standard_mix_project_with_supervision.yml
  .github/workflows/test_release_version.yml
  .github/workflows/test_template.yml
  .github/workflows/test_variant_on_custom_web_project.yml
  .github/workflows/test_variant_on_standard_web_project.yml
  lib/nimble_template/variants/phoenix/template.ex
  priv/templates/nimble_template/.github/workflows/test.yml.eex
  priv/templates/nimble_template/.github/workflows/test.yml.mix.eex
Labels: type : chore

#123 Order mix dependencies
  lib/nimble_template/helpers/dependency.ex
  lib/nimble_template/template.ex
  test/nimble_template/helpers/dependency_test.exs
Labels: type : feature

#119 Add prettier
  Makefile
  lib/nimble_template/addons/variants/phoenix/web/prettier.ex
  lib/nimble_template/addons/variants/phoenix/web/sobelow.ex
  lib/nimble_template/helpers/dependency.ex
  lib/nimble_template/template.ex
  lib/nimble_template/variants/phoenix/web/template.ex
  priv/templates/nimble_template/.prettierignore
  priv/templates/nimble_template/.prettierrc.yaml.eex
  test/nimble_template/addons/variants/phoenix/web/prettier_test.exs
  test/nimble_template/addons/variants/phoenix/web/sobelow_test.exs
Labels: type : feature

#132 Add Param Validation for the API project
  .github/workflows/test_api_variant_on_custom_api_project.yml
  .github/workflows/test_live_variant_on_custom_liveview_project.yml
  .github/workflows/test_mix_variant_on_custom_mix_project.yml
  .github/workflows/test_mix_variant_on_custom_mix_project_with_supervision.yml
  .github/workflows/test_variant_on_custom_web_project.yml
  README.md
  lib/nimble_template/addons/variants/phoenix/api/params_validation.ex
  lib/nimble_template/variants/phoenix/api/template.ex
  priv/templates/nimble_template/.credo.exs
  priv/templates/nimble_template/lib/otp_app_web/params/params.ex.eex
  priv/templates/nimble_template/lib/otp_app_web/params/params_validator.ex.eex
  priv/templates/nimble_template/test/otp_app_web/params/params_validator_test.exs.eex
  test/nimble_template/addons/variants/phoenix/api/params_validation_test.exs
  test/support/addon_case.ex
Labels: type : feature

#135 Migrate Wiki content to Github Workflow
  .github/PULL_REQUEST_TEMPLATE.md
  .github/wiki/Docker.md
  .github/wiki/Home.md
  .github/wiki/Testing.md
  .github/wiki/_Footer.md
  .github/wiki/_Sidebar.md
  .github/wiki/assets/images/.keep
  .github/workflows/publish_wiki.yml
  README.md
Labels: type : chore

#101 Add the workflow to deploy to Heroku and release PR template
  .gitignore
  Makefile
  lib/nimble_template/addons/github.ex
  lib/nimble_template/addons/variants/phoenix/web/wallaby.ex
  lib/nimble_template/helpers/github.ex
  lib/nimble_template/variants/mix/template.ex
  lib/nimble_template/variants/phoenix/template.ex
  priv/templates/nimble_template/.github/PULL_REQUEST_TEMPLATE.md
  priv/templates/nimble_template/.github/PULL_REQUEST_TEMPLATE/RELEASE_TEMPLATE.md
  priv/templates/nimble_template/.github/workflows/README.md
  priv/templates/nimble_template/.github/workflows/deploy_heroku.yml.eex
  priv/templates/nimble_template/README.md.eex
  priv/templates/nimble_template/README.md.mix.eex
  test/nimble_template/addons/github_test.exs
  test/nimble_template/addons/variants/phoenix/web/wallaby_test.exs
Labels: type : feature
