Repository nimblehq/elixir-templates, pull requests merged in 2021-04, with the labels that each got.

#79 Refactor the default version component
  .github/workflows/publish_to_hex_pm.yml
  .github/workflows/test_api_variant_on_custom_api_project.yml
  .github/workflows/test_api_variant_on_standard_api_project.yml
  .github/workflows/test_live_variant_on_custom_liveview_project.yml
  .github/workflows/test_live_variant_on_standard_liveview_project.yml
  .github/workflows/test_release_version.yml
  .github/workflows/test_template.yml
  .github/workflows/test_variant_on_custom_project.yml
  .github/workflows/test_variant_on_standard_project.yml
  .tool-versions
  README.md
  lib/nimble.phx.gen.template/addons/elixir_version.ex
  lib/nimble.phx.gen.template/addons/github.ex
  lib/nimble.phx.gen.template/addons/readme.ex
  lib/nimble.phx.gen.template/project.ex
  mix.exs
  priv/templates/nimble.phx.gen.template/.github/workflows/test.yml.eex
  priv/templates/nimble.phx.gen.template/.tool-versions.eex
  priv/templates/nimble.phx.gen.template/README.md.eex
  priv/templates/nimble.phx.gen.template/test/support/factory.ex.eex
  test/nimble.phx.gen.template/addons/docker_test.exs
  test/nimble.phx.gen.template/addons/elixir_version_test.exs
  test/nimble.phx.gen.template/addons/readme_test.exs
Labels: priority : high, type : chore

#91 Adding Github issue template
  .github/ISSUE_TEMPLATE/bug_template.md
  .github/ISSUE_TEMPLATE/feature_template.md
  .github/ISSUE_TEMPLATE/rfc_template.md
Labels: type : chore

#64 Adding Mix variant
  .github/workflows/test_api_variant_on_custom_api_project.yml
  .github/workflows/test_api_variant_on_standard_api_project.yml
  .github/workflows/test_live_variant_on_custom_liveview_project.yml
  .github/workflows/test_live_variant_on_standard_liveview_project.yml
  .github/workflows/test_mix_variant_on_custom_mix_project.yml
  .github/workflows/test_mix_variant_on_custom_mix_project_with_supervision.yml
  .github/workflows/test_mix_variant_on_standard_mix_project.yml
  .github/workflows/test_mix_variant_on_standard_mix_project_with_supervision.yml
  .github/workflows/test_variant_on_custom_web_project.yml
  .github/workflows/test_variant_on_standard_web_project.yml
  Makefile
  README.md
  action.yml
  lib/mix/tasks/nimble.phx.gen.template.ex
  lib/nimble.phx.gen.template/addons/credo.ex
  lib/nimble.phx.gen.template/addons/ex_coveralls.ex
  lib/nimble.phx.gen.template/addons/github.ex
  lib/nimble.phx.gen.template/addons/readme.ex
  lib/nimble.phx.gen.template/addons/test_env.ex
  lib/nimble.phx.gen.template/addons/variants/mix/.keep
  lib/nimble.phx.gen.template/project.ex
  lib/nimble.phx.gen.template/template.ex
  lib/nimble.phx.gen.template/variants/mix/template.ex
  mix.exs
  priv/templates/nimble.phx.gen.template/.github/workflows/test.yml.mix.eex
  priv/templates/nimble.phx.gen.template/README.md.mix.eex
  priv/templates/nimble.phx.gen.template/coveralls.json.mix.eex
  test/nimble.phx.gen.template/addons/credo_test.exs
  test/nimble.phx.gen.template/addons/ex_coveralls_test.exs
  test/nimble.phx.gen.template/addons/github_test.exs
  test/nimble.phx.gen.template/addons/readme_test.exs
  test/nimble.phx.gen.template/addons/test_env_test.exs
  test/nimble.phx.gen.template/addons/variants/live/.keep
  test/nimble.phx.gen.template/addons/variants/mix/.keep
  test/support/addon_case.ex
Labels: type : feature

#90 Adding ExVCR addon
  Makefile
  lib/nimble_template/addons/ex_vcr.ex
  lib/nimble_template/generator.ex
  lib/nimble_template/template.ex
  test/nimble_template/addons/ex_vcr_test.exs
Labels: type : feature

#95 Refactor the Github action flows
  .github/workflows/publish_to_hex_pm.yml
  .github/workflows/test_api_variant_on_custom_api_project.yml
  .github/workflows/test_api_variant_on_standard_api_project.yml
  .github/workflows/test_live_variant_on_custom_liveview_project.yml
  .github/workflows/test_live_variant_on_standard_liveview_project.yml
  .github/workflows/test_mix_variant_on_custom_mix_project.yml
  .github/workflows/test_mix_variant_on_custom_mix_project_with_supervision.yml
  .github/workflows/test_mix_variant_on_standard_mix_project.yml
  .github/workflows/test_mix_variant_on_standard_mix_project_with_supervision.yml
  .github/workflows/test_release_version.yml
  .github/workflows/test_template.yml
  .github/workflows/test_variant_on_custom_web_project.yml
  .github/workflows/test_variant_on_standard_web_project.yml
  Makefile
  action.yml
  priv/templates/nimble_template/.github/workflows/test.yml.eex
  priv/templates/nimble_template/.github/workflows/test.yml.mix.eex
Labels: type : chore

#92 Refactor the variant folder structure
  README.md
  lib/nimble_template/addons/variants/phoenix/api/.keep
  lib/nimble_template/addons/variants/phoenix/live/.keep
  lib/nimble_template/addons/variants/phoenix/web/assets.ex
  lib/nimble_template/addons/variants/phoenix/web/core_js.ex
  lib/nimble_template/addons/variants/phoenix/web/sobelow.ex
  lib/nimble_template/addons/variants/phoenix/web/wallaby.ex
  lib/nimble_template/template.ex
  lib/nimble_template/variants/phoenix/api/template.ex
  lib/nimble_template/variants/phoenix/live/template.ex
  lib/nimble_template/variants/phoenix/template.ex
  lib/nimble_template/variants/phoenix/web/template.ex
  test/nimble_template/addons/credo_test.exs
  test/nimble_template/addons/dialyxir_test.exs
  test/nimble_template/addons/docker_test.exs
  test/nimble_template/addons/elixir_version_test.exs
  test/nimble_template/addons/ex_coveralls_test.exs
  test/nimble_template/addons/ex_machina_test.exs
  test/nimble_template/addons/github_test.exs
  test/nimble_template/addons/makefile_test.exs
  test/nimble_template/addons/mimic_test.exs
  test/nimble_template/addons/mix_release_test.exs
  test/nimble_template/addons/oban_test.exs
  test/nimble_template/addons/readme_test.exs
  test/nimble_template/addons/test_env_test.exs
  test/nimble_template/addons/variants/phoenix/api/.keep
  test/nimble_template/addons/variants/phoenix/live/.keep
  test/nimble_template/addons/variants/phoenix/web/assets_test.exs
  test/nimble_template/addons/variants/phoenix/web/core_js_test.exs
  test/nimble_template/addons/variants/phoenix/web/sobelow_test.exs
  test/nimble_template/addons/variants/phoenix/web/wallaby_test.exs
  test/support/addon_case.ex
Labels: type : chore

#93 Adding capture_log: true
  .github/workflows/publish_to_hex_pm.yml
  .github/workflows/test_api_variant_on_custom_api_project.yml
  .github/workflows/test_api_variant_on_standard_api_project.yml
  .github/workflows/test_live_variant_on_custom_liveview_project.yml
  .github/workflows/test_live_variant_on_standard_liveview_project.yml
  .github/workflows/test_mix_variant_on_custom_mix_project.yml
  .github/workflows/test_mix_variant_on_custom_mix_project_with_supervision.yml
  .github/workflows/test_mix_variant_on_standard_mix_project.yml
  .github/workflows/test_mix_variant_on_standard_mix_project_with_supervision.yml
  .github/workflows/test_release_version.yml
  .github/workflows/test_template.yml
  .github/workflows/test_variant_on_custom_web_project.yml
  .github/workflows/test_variant_on_standard_web_project.yml
  Makefile
  action.yml
  lib/nimble_template/addons/ex_unit.ex
  lib/nimble_template/variants/mix/template.ex
  lib/nimble_template/variants/phoenix/template.ex
  priv/templates/nimble_template/.github/workflows/test.yml.eex
  priv/templates/nimble_template/.github/workflows/test.yml.mix.eex
  test/nimble_template/addons/ex_unit_test.exs
  test/test_helper.exs
Labels: type : feature

#97 Upgrade dependency before rollout 3.0.0
  mix.exs
  mix.lock
Labels: type : chore

#94 Refactor the Dockerfile
  lib/nimble_template/addons/docker.ex
  lib/nimble_template/project.ex
  priv/templates/nimble_template/Dockerfile.eex
  test/nimble_template/addons/docker_test.exs
Labels: type : chore

#99 Add .keep file when creating worker directory
  lib/nimble_template/addons/oban.ex
  test/nimble_template/addons/oban_test.exs
Labels: type : chore
