Repository nimblehq/elixir-templates, pull requests merged in 2021-03, with the labels that each got.

#82 Tweak Github Action
  .github/workflows/publish_to_hex_pm.yml
  .github/workflows/test_api_variant_on_custom_api_project.yml
  .github/workflows/test_api_variant_on_standard_api_project.yml
  .github/workflows/test_live_variant_on_custom_liveview_project.yml
  .github/workflows/test_live_variant_on_standard_liveview_project.yml
  .github/workflows/test_release_version.yml
  .github/workflows/test_template.yml
  .github/workflows/test_variant_on_custom_project.yml
  .github/workflows/test_variant_on_standard_project.yml
  priv/templates/nimble.phx.gen.template/.github/workflows/test.yml.eex
Labels: priority : high, type : chore

#87 Increase version to 2.2.1
  mix.exs
Labels: priority : high, type : chore

#84 Change the first app name in mix phx.new to lower key
  README.md
Labels: type : chore

#86 Release - 2.2.1
  .github/workflows/publish_to_hex_pm.yml
  .github/workflows/test_api_variant_on_custom_api_project.yml
  .github/workflows/test_api_variant_on_standard_api_project.yml
  .github/workflows/test_live_variant_on_custom_liveview_project.yml
  .github/workflows/test_live_variant_on_standard_liveview_project.yml
  .github/workflows/test_release_version.yml
  .github/workflows/test_template.yml
  .github/workflows/test_variant_on_custom_project.yml
  .github/workflows/test_variant_on_standard_project.yml
  .tool-versions
  LICENSE
  README.md
  lib/nimble.phx.gen.template/project.ex
  mix.exs
  mix.lock
  priv/templates/nimble.phx.gen.template/.github/workflows/test.yml.eex
  priv/templates/nimble.phx.gen.template/README.md.eex
  test/nimble.phx.gen.template/addons/docker_test.exs
  test/nimble.phx.gen.template/addons/elixir_version_test.exs
  test/nimble.phx.gen.template/addons/readme_test.exs
Labels: priority : high, type : release

#83 Update README Structure and typo
  README.md
Labels: type : chore
