Repository nimblehq/elixir-templates, pull requests merged in 2022-09, with the labels that each got.

#263 [Chore] Bump version to 4.4.0
  README.md
  mix.exs
Labels: type : chore

#264 [gh-253] Do not render the ExVCR in FeatureCase
  lib/nimble_template/addons/addon.ex
  lib/nimble_template/addons/variants/phoenix/web/wallaby.ex
  lib/nimble_template/helpers/project.ex
  lib/nimble_template/projects/project.ex
  priv/templates/nimble_template/.github/workflows/README.md.eex
  priv/templates/nimble_template/test/support/feature_case.ex.eex
  test/nimble_template/addons/asdf_tool_version_test.exs
  test/nimble_template/addons/variants/phoenix/web/wallaby_test.exs
  test/support/addon_case.ex
Labels: type : bug

#257 [Chore] Upgrade version for Elixir, Erlang
  .tool-versions
  README.md
  lib/nimble_template/addons/variants/phoenix/health_plug.ex
  lib/nimble_template/addons/variants/phoenix/web/wallaby.ex
  lib/nimble_template/projects/project.ex
  mix.exs
  test/nimble_template/addons/asdf_tool_version_test.exs
  test/nimble_template/addons/github_test.exs
  test/nimble_template/addons/readme_test.exs
  test/nimble_template/addons/variants/docker_test.exs
  test/nimble_template/addons/variants/health_plug_test.exs
  test/nimble_template/addons/variants/phoenix/web/wallaby_test.exs
Labels: type : chore

#266 [gh-265] Add the IEx addon
  .github/ISSUE_TEMPLATE/rfc_template.md
  lib/nimble_template/addons/git.ex
  lib/nimble_template/addons/iex.ex
  lib/nimble_template/templates/variants/mix/template.ex
  lib/nimble_template/templates/variants/phoenix/template.ex
  priv/templates/nimble_template/.iex.exs.eex
  test/nimble_template/addons/git_test.exs
  test/nimble_template/addons/iex_test.exs
Labels: type : chore

#278 Release - 4.4.0
  .credo.exs
  .github/ISSUE_TEMPLATE/rfc_template.md
  .tool-versions
  README.md
  lib/nimble_template/addons/addon.ex
  lib/nimble_template/addons/git.ex
  lib/nimble_template/addons/iex.ex
  lib/nimble_template/addons/variants/phoenix/api/config.ex
  lib/nimble_template/addons/variants/phoenix/api/json_api.ex
  lib/nimble_template/addons/variants/phoenix/ex_machina.ex
  lib/nimble_template/addons/variants/phoenix/health_plug.ex
  lib/nimble_template/addons/variants/phoenix/web/core_js.ex
  lib/nimble_template/addons/variants/phoenix/web/es_lint.ex
  lib/nimble_template/addons/variants/phoenix/web/wallaby.ex
  lib/nimble_template/helpers/project.ex
  lib/nimble_template/projects/project.ex
  lib/nimble_template/templates/variants/mix/template.ex
  lib/nimble_template/templates/variants/phoenix/template.ex
  mix.exs
  mix.lock
  priv/templates/nimble_template/.credo.exs
  priv/templates/nimble_template/.github/workflows/README.md.eex
  priv/templates/nimble_template/.iex.exs.eex
  priv/templates/nimble_template/test/support/feature_case.ex.eex
  test/nimble_template/addons/asdf_tool_version_test.exs
  test/nimble_template/addons/git_test.exs
  test/nimble_template/addons/github_test.exs
  test/nimble_template/addons/iex_test.exs
  test/nimble_template/addons/readme_test.exs
  test/nimble_template/addons/variants/docker_test.exs
  test/nimble_template/addons/variants/health_plug_test.exs
  test/nimble_template/addons/variants/phoenix/web/wallaby_test.exs
  test/support/addon_case.ex
Labels: type : release
