Repository nimblehq/elixir-templates, pull requests merged in 2022-11, with the labels that each got.

#281 [#194] Update the Workflows README about the Publish Wiki Workflow
  lib/nimble_template/addons/github.ex
  lib/nimble_template/templates/variants/mix/template.ex
  lib/nimble_template/templates/variants/phoenix/template.ex
  priv/templates/nimble_template/.github/workflows/README.md.eex
  test/nimble_template/addons/github_test.exs
Labels: type : feature

#283 Fix Codeowner file
  .github/CODEOWNERS
Labels: type : chore

#280 [#279] Fix: Invalid "Project" struct when initializing Elixir project with custom module name
  .credo.exs
  lib/nimble_template/projects/project.ex
  test/nimble_template/projects/project_test.exs
  test/support/addon_case.ex
Labels: type : bug

#285 [gh-249] Fix infinity loop on Upgrade stack
  lib/nimble_template/helpers/generator.ex
Labels: type : bug

#290 Revisit the  `compile_env` in `router.ex` file
  lib/nimble_template/addons/variants/phoenix/health_plug.ex
  priv/templates/nimble_template/lib/otp_app_web/helpers/icon_helper.ex.eex
  priv/templates/nimble_template/lib/otp_app_web/helpers/router_helper.ex.eex
  priv/templates/nimble_template/test/otp_app_web/helpers/router_helper_test.exs.eex
  test/nimble_template/addons/variants/health_plug_test.exs
Labels: priority : high, type : bug

#276 [#277] Add Compass Credo check plugin
  lib/nimble_template/addons/addon.ex
  lib/nimble_template/addons/credo.ex
  lib/nimble_template/addons/variants/phoenix/oban.ex
  lib/nimble_template/addons/variants/phoenix/web/wallaby.ex
  lib/nimble_template/helpers/credo.ex
  lib/nimble_template/helpers/generator.ex
  lib/nimble_template/templates/template.ex
  priv/templates/nimble_template/.credo.exs
  test/nimble_template/addons/credo_test.exs
  test/nimble_template/addons/variants/oban_test.exs
  test/nimble_template/addons/variants/phoenix/web/wallaby_test.exs
  test/nimble_template/helpers/credo_test.exs
  test/nimble_template/helpers/generator_test.exs
Labels: type : feature

#295 [Chore] Bump version to 4.5.0
  README.md
  mix.exs
Labels: type : chore

#296 Release - 4.5.0
  .credo.exs
  .github/CODEOWNERS
  README.md
  lib/nimble_template/addons/addon.ex
  lib/nimble_template/addons/credo.ex
  lib/nimble_template/addons/github.ex
  lib/nimble_template/addons/variants/phoenix/health_plug.ex
  lib/nimble_template/addons/variants/phoenix/oban.ex
  lib/nimble_template/addons/variants/phoenix/web/wallaby.ex
  lib/nimble_template/helpers/credo.ex
  lib/nimble_template/helpers/generator.ex
  lib/nimble_template/projects/project.ex
  lib/nimble_template/templates/template.ex
  lib/nimble_template/templates/variants/mix/template.ex
  lib/nimble_template/templates/variants/phoenix/template.ex
  mix.exs
  priv/templates/nimble_template/.credo.exs
  priv/templates/nimble_template/.github/workflows/README.md.eex
  priv/templates/nimble_template/lib/otp_app_web/helpers/icon_helper.ex.eex
  priv/templates/nimble_template/lib/otp_app_web/helpers/router_helper.ex.eex
  priv/templates/nimble_template/test/otp_app_web/helpers/router_helper_test.exs.eex
  test/nimble_template/addons/credo_test.exs
  test/nimble_template/addons/github_test.exs
  test/nimble_template/addons/variants/health_plug_test.exs
  test/nimble_template/addons/variants/oban_test.exs
  test/nimble_template/addons/variants/phoenix/web/wallaby_test.exs
  test/nimble_template/helpers/credo_test.exs
  test/nimble_template/helpers/generator_test.exs
  test/nimble_template/projects/project_test.exs
  test/support/addon_case.ex
Labels: type : release

#284 Do not allow the Test ENV call Hex.pm directly
  .github/workflows/reusable_mix_project.yml
  .github/workflows/reusable_phoenix_project.yml
  config/config.exs
  config/test.exs
  lib/nimble_template/addons/addon.ex
  lib/nimble_template/exception/mock_hex_package_required.ex
  lib/nimble_template/hex/package.ex
  lib/nimble_template/hex/package_behaviour.ex
  lib/nimble_template/hex/package_mock.ex
  test/nimble_template/addons/credo_test.exs
  test/nimble_template/addons/variants/health_plug_test.exs
  test/nimble_template/addons/variants/phoenix/web/bootstrap_test.exs
  test/nimble_template/hex/package_mock_test.exs.exs
  test/support/addon_case.ex
  test/test_helper.exs
Labels: type : chore
