Repository nimblehq/elixir-templates, pull requests merged in 2022-03, with the labels that each got.

#161 Add Bootstrap
  Makefile
  lib/nimble_template/addons/variants/phoenix/web/bootstrap.ex
  lib/nimble_template/addons/variants/phoenix/web/dart_sass.ex
  lib/nimble_template/addons/variants/phoenix/web/nimble_css.ex
  lib/nimble_template/addons/variants/phoenix/web/nimble_js.ex
  lib/nimble_template/helpers/addon.ex
  lib/nimble_template/helpers/generator.ex
  lib/nimble_template/templates/variants/phoenix/web/template.ex
  mix.exs
  priv/templates/nimble_template/.github/workflows/README.md.eex
  priv/templates/nimble_template/.github/workflows/test.yml.eex
  priv/templates/nimble_template/Dockerfile.eex
  priv/templates/nimble_template/assets/bootstrap_css/vendor/_bootstrap.scss
  priv/templates/nimble_template/assets/nimble_css/_variables.scss
  priv/templates/nimble_template/assets/nimble_css/app.scss
  priv/templates/nimble_template/assets/nimble_css/base/_index.scss
  priv/templates/nimble_template/assets/nimble_css/components/_index.scss
  priv/templates/nimble_template/assets/nimble_css/functions/_index.scss
  priv/templates/nimble_template/assets/nimble_css/functions/_sizing.scss
  priv/templates/nimble_template/assets/nimble_css/layouts/_default.scss
  priv/templates/nimble_template/assets/nimble_css/layouts/_index.scss
  priv/templates/nimble_template/assets/nimble_css/mixins/_index.scss
  priv/templates/nimble_template/assets/nimble_css/mixins/_text-ellipsis.scss
  priv/templates/nimble_template/assets/nimble_css/screens/_index.scss
  priv/templates/nimble_template/assets/nimble_css/vendor/_index.scss
  priv/templates/nimble_template/assets/nimble_js/adapters/.keep
  priv/templates/nimble_template/assets/nimble_js/components/.keep
  priv/templates/nimble_template/assets/nimble_js/config/.keep
  priv/templates/nimble_template/assets/nimble_js/helpers/event.js
  priv/templates/nimble_template/assets/nimble_js/helpers/screen.js
  priv/templates/nimble_template/assets/nimble_js/initializers/index.js
  priv/templates/nimble_template/assets/nimble_js/lib/.keep
  priv/templates/nimble_template/assets/nimble_js/screens/index.js
  test/nimble_template/addons/github_test.exs
  test/nimble_template/addons/variants/phoenix/web/bootstrap_test.exs
  test/nimble_template/addons/variants/phoenix/web/dart_sass_test.exs
  test/nimble_template/addons/variants/phoenix/web/nimble_css_test.exs
  test/nimble_template/addons/variants/phoenix/web/nimble_js_test.exs
Labels: priority : high

#172 Reduce the partition to 1 as at beginning we have only 1 feature test
  priv/templates/nimble_template/.github/workflows/test.yml.eex
Labels: priority : high

#173 Adjust the Heroku, Release, and Assets addon to make the app deployable
  lib/nimble_template/addons/github.ex
  lib/nimble_template/addons/variants/phoenix/mix_release.ex
  priv/templates/nimble_template/.dockerignore
  priv/templates/nimble_template/.github/wiki/Environment-Variables.md.eex
  priv/templates/nimble_template/.github/workflows/README.md.eex
  test/nimble_template/addons/github_test.exs
  test/nimble_template/addons/variants/mix_release_test.exs
Labels: priority : high

#176 Update Gettext addon
  lib/nimble_template/addons/variants/phoenix/gettext.ex
  priv/templates/nimble_template/.github/workflows/test.yml.eex
  test/nimble_template/addons/variants/gettext_test.exs
Labels: priority : high

#175 Add a Wiki document on how to get started and contribute to Elixir template
  .github/wiki/Contribution.md
  .github/wiki/_Sidebar.md
  .github/wiki/assets/images/.keep
  .github/wiki/assets/images/addon-structure.png
Labels: type : feature

#171 Add Wiki document on how to generate a sample project on development
  .github/wiki/Contribution.md
  .github/wiki/Generation.md
  .github/wiki/_Sidebar.md
Labels: type : feature

#181 Release - 0.4.1
  .github/wiki/Contribution.md
  .github/wiki/Generation.md
  .github/wiki/_Sidebar.md
  .github/wiki/assets/images/.keep
  .github/wiki/assets/images/addon-structure.png
  README.md
  lib/nimble_template/addons/variants/phoenix/api/fallback_controller.ex
  mix.exs
  priv/templates/nimble_template/Dockerfile.eex
  priv/templates/nimble_template/lib/otp_app_web/controllers/api/fallback_controller.ex.eex
  test/nimble_template/addons/variants/docker_test.exs
  test/nimble_template/addons/variants/phoenix/api/fallback_controller_test.exs
Labels: type : release

#190 Add the project's maintainers info
  .github/CODEOWNERS
Labels: type : chore

#192 Update Postgres Image version to 14.2
  .github/workflows/reusable_phoenix_project.yml
  priv/templates/nimble_template/.github/workflows/test.yml.eex
  priv/templates/nimble_template/docker-compose.dev.yml.eex
  test/nimble_template/addons/variants/docker_test.exs
Labels: type : feature
